// Map car names to local image filenames
export const carImageMap = {
  'Toyota Axio': 'toyota axio.jpeg',
  'Nissan Sunny': 'nissan-sunny.jpg',
  'Toyota Prado': 'toyota-prado.jpg',
  'Honda Fit': 'honda-fit.jpg',
  'Mitsubishi L200': 'mitsubishi-l200.jpg',
  'Toyota Hiace': 'toyota-hiace.jpg',
  'Subaru Forester': 'subaru-forester.jpg',
  'Mazda Demio': 'mazda-demio.jpg',
  'Nissan Patrol': 'nissan-patrol.jpg',
  'Toyota Corolla': 'toyota-corolla.jpg',
  'Honda CR-V': 'honda-cr-v.jpg',
  'Isuzu D-Max': 'isuzu-d-max.jpg',
  'Hyundai Tucson': 'hyundai-tucson.jpg',
  'Kia Sportage': 'kia-sportage.jpg',
  'Mercedes-Benz C-Class': 'mercedes-benz-c-class.jpg',
  'BMW X3': 'bmw-x3.jpg',
  'Audi A4': 'audi-a4.jpg',
  'Volkswagen Golf': 'volkswagen-golf.jpg',
  'Ford Ranger': 'ford-ranger.jpg',
  'Toyota Land Cruiser': 'toyota-land-cruiser.jpg',
  'Toyota Allion': 'toyota-allion.jpg',
  'Suzuki Swift': 'suzuki-swift.jpg',
  'Renault Duster': 'renault-duster.jpg',
  'Datsun Go': 'datsun-go.jpg',
  'Mahindra Bolero': 'mahindra-bolero.jpg',
  'Chevrolet Cruze': 'chevrolet-cruze.jpg',
  'Hyundai i10': 'hyundai-i10.jpg',
  'Toyota Mark X': 'toyota-mark-x.jpg',
  'Mitsubishi Outlander': 'mitsubishi-outlander.jpg',
  'Nissan X-Trail': 'nissan-x-trail.jpg',
  'Toyota Vitz': 'toyota-vitz.jpg',
  'Kia Picanto': 'kia-picanto.jpg',
  'Toyota RAV4': 'toyota-rav4.jpg',
  'Toyota Camry': 'toyota-camry.jpg',
  'Toyota Fortuner': 'toyota-fortuner.jpg',
  'Toyota Wish': 'toyota-wish.jpg',
  'Toyota Land Cruiser Prado TX': 'toyota-land-cruiser-prado-tx.jpg',
  'Toyota Land Cruiser V8': 'toyota-land-cruiser-v8.jpg',
  'Toyota Land Cruiser 300': 'toyota-land-cruiser-300.jpg',
  'Nissan Qashqai': 'nissan-qashqai.jpg',
  'Nissan Altima': 'nissan-altima.jpg',
  'Nissan Murano': 'nissan-murano.jpg',
  'Nissan Rogue': 'nissan-rogue.jpg',
  'Nissan Frontier': 'nissan-frontier.jpg',
  'Subaru Outback': 'subaru-outback.jpg',
  'Subaru Impreza': 'subaru-impreza.jpg',
  'Subaru XV': 'subaru-xv.jpg',
  'Subaru Legacy': 'subaru-legacy.jpg',
  'Porsche 911': 'porsche-911.jpg',
  'Porsche Cayenne': 'porsche-cayenne.jpg',
  'Porsche Panamera': 'porsche-panamera.jpg',
  'Porsche Boxster': 'porsche-boxster.jpg',
  'Porsche Macan': 'porsche-macan.jpg',
  'Porsche Cayman': 'porsche-cayman.jpg',
  'BMW 3 Series': 'bmw-3-series.jpg',
  'BMW 5 Series': 'bmw-5-series.jpg',
  'BMW X5': 'bmw-x5.jpg',
  'BMW X7': 'bmw-x7.jpg',
  'BMW 7 Series': 'bmw-7-series.jpg',
  'BMW X1': 'bmw-x1.jpg',
  'BMW M440i': 'bmw-m440i.jpg',
  'BMW i7': 'bmw-i7.jpg',
  'BMW M2': 'bmw-m2.jpg',
  'BMW M3': 'bmw-m3.jpg',
  'BMW M4': 'bmw-m4.jpg',
  'BMW M5': 'bmw-m5.jpg',
  'BMW M550i': 'bmw-m550i.jpg',
  'BMW XM': 'bmw-xm.jpg',
  'BMW M8': 'bmw-m8.jpg',
  'Toyota Probox': 'toyota-probox.jpg',
  'Toyota Hilux': 'toyota-hilux.jpg',
  'Nissan NV200': 'nissan-nv200.jpg',
  'Mazda Axela': 'mazda-axela.jpg',
  'Suzuki Alto': 'suzuki-alto.jpg',
  'Toyota Fielder': 'toyota-fielder.jpg',
  'Nissan Wingroad': 'nissan-wingroad.jpg',
  'Mitsubishi RVR': 'mitsubishi-rvr.jpg',
  'Nissan Note': 'nissan-note.jpg',
  'Honda Vezel': 'honda-vezel.jpg',
  'Toyota Noah': 'toyota-noah.jpg',
  'Nissan Serena': 'nissan-serena.jpg',
  'Mazda Atenza': 'mazda-atenza.jpg',
  'Subaru WRX': 'subaru-wrx.jpg',
  'Toyota Harrier': 'toyota-harrier.jpg',
  'Nissan Tiida': 'nissan-tiida.jpg',
  'Mazda CX-5': 'mazda-cx-5.jpg',
  'Honda Accord': 'honda-accord.jpg',
  'Toyota Premio': 'toyota-premio.jpg',
  'Nissan Juke': 'nissan-juke.jpg',
  'Volkswagen Tiguan': 'volkswagen-tiguan.jpg',
  'Land Rover Discovery': 'land-rover-discovery.jpg',
  'Mercedes-Benz E-Class': 'mercedes-benz-e-class.jpg',
  'Audi Q5': 'audi-q5.jpg',
  'Lexus RX 350': 'lexus-rx-350.jpg',
  'Toyota Crown': 'toyota-crown.jpg',
  'Mitsubishi Pajero': 'mitsubishi-pajero.jpg',
  'Volkswagen Passat': 'volkswagen-passat.jpg',
  'Mazda CX-3': 'mazda-cx-3.jpg',
  'Honda HR-V': 'honda-hr-v.jpg',
  'Range Rover Sport': 'range-rover-sport.jpg',
  'Mazda 2': 'mazda-2.jpg',
  'Mazda 3': 'mazda-3.jpg',
  'Mazda 6': 'mazda-6.jpg',
  'Mazda Premacy': 'mazda-premacy.jpg',
  'Mazda Biante': 'mazda-biante.jpg',
  'Mazda Verisa': 'mazda-verisa.jpg',
  'Mazda CX-7': 'mazda-cx-7.jpg',
  'Mazda CX-9': 'mazda-cx-9.jpg',
  'Mazda CX-30': 'mazda-cx-30.jpg',
  'Mazda MX-5 Miata': 'mazda-mx-5-miata.jpg',
  'Mazda Carol': 'mazda-carol.jpg',
  'Mazda CX-8': 'mazda-cx-8.jpg',
}

const carImageModules = import.meta.glob('./assets/cars/*.{jpg,jpeg,png,webp}', {
  eager: true,
  import: 'default'
})

const carImagesByFile = Object.fromEntries(
  Object.entries(carImageModules).map(([path, url]) => [path.split('/').pop(), url])
)

export const getCarImagePath = (carName, fallback = null) => {
  const imageName = carImageMap[carName]
  if (imageName && carImagesByFile[imageName]) {
    return carImagesByFile[imageName]
  }
  return fallback
}
